AB2D-6912 Update terraform/tofu to remove properties service  (#1646)
## 🎫 Ticket

https://jira.cms.gov/browse/AB2D-6912

## 🛠 Changes

- Remove module related to properties service
- Update/remove references to properties service

## ℹ️ Context

As part of [AB2D-6720](https://jira.cms.gov/browse/AB2D-6720), the
properties service was deprecated and no longer called from any apps.
The properties service API was updated to (a) return empty responses to
ensure services are not relying on properties API and (b) log when an
endpoint is invoked to verify apps are not invoking the API.

This PR removes all terraform/tofu modules related to the properties
service.

## Terraform

Run the following to generate the plan:

```
cd ops/services/20-microservices

export ENV=dev

tofu init -var=parent_env=$ENV -reconfigure

tofu workspace select -var=parent_env=$ENV -or-create=true $ENV

tofu plan -var=parent_env=$ENV -out=tfplan
```

**NOTE**: Running tofu apply multiple times seems to be necessary. This
error will occur but will eventually go away:
```
Error: deleting ELBv2 Target Group (arn:aws:elasticloadbalancing:us-east-1:XXXXXXXXX:targetgroup/ab2d-dev-properties/8731dfe063afbac3): operation error Elastic Load Balancing v2: DeleteTargetGroup, https response error StatusCode: 400, RequestID: 60089060-749c-4db1-a036-55c914e8efae, ResourceInUse: Target group 'arn:aws:elasticloadbalancing:us-east-1:XXXXXXXXX:targetgroup/ab2d-dev-properties/8731dfe063afbac3' is currently in use by a listener or a rule
```

## 🧪 Validation

E2E BFD tests: https://github.com/CMSgov/ab2d/actions/runs/19379292478

E2E tests: https://github.com/CMSgov/ab2d/actions/runs/19379295303

Applied changes successfully. Load balancer shows the default rule for
properties is removed:

<img width="1274" height="269" alt="image"
src="https://github.com/user-attachments/assets/5d7dacf3-9fe7-4ebd-8294-f6f08aa09204"
/>

Microservices cluster shows only contracts and events:
<img width="1216" height="223" alt="image"
src="https://github.com/user-attachments/assets/f415cf08-48aa-4c92-a2d0-37cb8fe54403"
/>