AB2D-7123 Building locally (#1711)
## 🎫 Ticket

https://jira.cms.gov/browse/AB2D-7123

## 🛠 Changes

Fixes a variety of errors, some preemptively. 

- `BulkDataAccessAPIIntegrationTests` clears timestamps, when the minute
rolls over it can mismatch
- `DataSetup` and `WorkerDataSetup` use increment instead of rng to
prevent test collisions
- `SQSConfig` and `SNSConfig` use local credentials when in local
environment
- `CoverageDriverTest` avoid race condition with processor shutdown, and
bonus speedup to test
- `JobCleanup` updated to ensure a clean database state between test
runs.
- `application.properties` reduce number of warning logs with settings
changes
- `ContractProcessorUnitTest` now mocks aggregator, since it would
sometimes cause a race condition

Also CoverageDataSetup's sleep was replaced with a poll so it's much
faster now.

## ℹ️ Context

Several of the tests were producing nondeterministic errors when run. I
address these errors in two main changes. The first mocks the Aggregator
in ContractProcessorUnitTest. My interpretation of the error related to
this test, e.g.:
```[ERROR] Surefire is going to kill self fork JVM. The exit has elapsed 30 seconds after System.exit(0).
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ContractProcessorUnitTest.testIsDone:149 expected: <false> but was: <true>
```

Was that it was related to running the aggregator in a background
thread. The `isDone` should not be tested with a live aggregator running
in the background, so we can mock the aggregator and feed into the
tested function exactly the state that is needed to see if the function
returns the expected response.

The other nondeterministic errors were more varied:

```
[ERROR] Errors: 
[ERROR]   CoverageDriverTest.getNextSearchDefaultsToFirst:570 » NoSuchElement No value present
```
```
[ERROR] Errors: 
[ERROR]   CoverageDriverTest.cleanup:198 » DataIntegrityViolation could not execute statement [ERROR: update or delete on table "bene_coverage_period" violates foreign key constraint "fk_bene_coverage_search_update_to_bene_coverage_period" on table "event_bene_coverage_search_status_change"                                                                       
  Detail: Key (id)=(82) is still referenced from table "event_bene_coverage_search_status_change".] [delete from bene_coverage_period where id=?]; SQL [delete from bene_coverage_period where id=?]; constraint [fk_bene_coverage_search_update_to_bene_coverage_period]                                                                                                 
[INFO] 
[ERROR] Tests run: 251, Failures: 0, Errors: 1, Skipped: 1
```
```
[ERROR] Surefire is going to kill self fork JVM. The exit has elapsed 30 seconds after System.exit(0).
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   CoverageUpdateAndProcessorTest.discoverCoveragePeriods:208 expected: <74> but was: <3>
[INFO] 
```
My theory is that background process is still in the process of making a
submission after the repository clears in the `cleanup` function. I.e.
we are not in shutdown -> attempt coverage insertion -> we enter
shutdown midway -> cleanup starts happening -> coverage insertion occurs
at inconvenient time -> error. But transient errors are difficult to
debug and I am still learning how everything connects. Either way, I
have not seen these errors again.

## 🧪 Validation

The tests run without issue, and have been successful for 15+ runs.